import { Course } from '../types';

export const IEFP_MASSIVE_DATABASE: Course[] = [
    // Cursos de Aprendizagem (IEFP)
    { id: 'appr-1', title: 'Técnico de Informática - Instalação e Gestão de Redes', description: 'Curso de aprendizagem jovem. Desenvolva competências em sistemas informáticos e redes.', category: 'Educação & Qualificação', type: 'Presencial', duration: '3200h', image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80', isIefpSynced: true, link: 'https://www.iefp.pt/cursos-de-aprendizagem1' },
    { id: 'appr-2', title: 'Técnico de Multimédia', description: 'Criação de produtos multimédia interactivos, vídeo e som. Formação financiada.', category: 'Tecnologia & Inovação', type: 'Híbrido', duration: '3700h', image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&q=80', isIefpSynced: true, link: 'https://www.iefp.pt/cursos-de-aprendizagem1' },
    { id: 'appr-3', title: 'Técnico Administrativo e de Recursos Humanos', description: 'Gestão de processos administrativos e apoio aos recursos humanos das empresas.', category: 'Empreendedorismo', type: 'Presencial', duration: '3100h', image: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&q=80', isIefpSynced: true, link: 'https://www.iefp.pt/cursos-de-aprendizagem1' },
    { id: 'appr-4', title: 'Técnico de Cozinha/Pastelaria', description: 'Aprenda técnicas de cozinha avançadas num curso 100% focado no saber-fazer.', category: 'Emprego & Negócios', type: 'Presencial', duration: '3000h', image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&q=80', isIefpSynced: true, link: 'https://www.iefp.pt/cursos-de-aprendizagem1' },
    { id: 'appr-5', title: 'Técnico de Energias Renováveis (Eólica)', description: 'Oportunidade de carreira numa área de forte expansão no mercado europeu.', category: 'Emprego & Negócios', type: 'Presencial', duration: '2800h', image: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=800&q=80', isIefpSynced: true, link: 'https://www.iefp.pt/cursos-de-aprendizagem1' },

    // Cursos EFA (Educação e Formação para Adultos)
    { id: 'efa-1', title: 'Técnico de Logística - Nível IV', description: 'Formação EFA para adultos. Gestão de armazéns e rotas de distribuição.', category: 'Emprego & Negócios', type: 'Presencial', duration: '1200h', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80', isIefpSynced: true, link: 'https://www.iefp.pt/cursos-de-educacao-e-formacao-para-adultos' },
    { id: 'efa-2', title: 'Cuidador de Crianças e Jovens', description: 'Apoio social e cuidados a crianças. Forte empregabilidade imediata.', category: 'Saúde & Bem-estar', type: 'Presencial', duration: '900h', image: 'https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?w=800&q=80', isIefpSynced: true, link: 'https://www.iefp.pt/cursos-de-educacao-e-formacao-para-adultos' },
    { id: 'efa-3', title: 'Técnico de Design Gráfico', description: 'Domínio das ferramentas Adobe e princípios do design para web e print.', category: 'Tecnologia & Inovação', type: 'Online', duration: '850h', image: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800&q=80', isIefpSynced: true, link: 'https://www.iefp.pt/cursos-de-educacao-e-formacao-para-adultos' },
    { id: 'efa-4', title: 'Operador de Máquinas e CNC', description: 'Curso EFA virado para o sector industrial. Torno e Fresadora CNC.', category: 'Emprego & Negócios', type: 'Presencial', duration: '1100h', image: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800&q=80', isIefpSynced: true, link: 'https://www.iefp.pt/cursos-de-educacao-e-formacao-para-adultos' },
    { id: 'efa-5', title: 'Técnico de Instalações Elétricas', description: 'Certificação DGEG. Um dos perfis com maior procura no mercado imobiliário e indústria.', category: 'Emprego & Negócios', type: 'Presencial', duration: '1500h', image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80', isIefpSynced: true, link: 'https://www.iefp.pt/cursos-de-educacao-e-formacao-para-adultos' },

    // Passaporte Qualifica / Centro Qualifica
    { id: 'qual-1', title: 'Processo RVCC Escolar - 9º Ano', description: 'Conclua o ensino básico reconhecendo as suas competências profissionais e de vida.', category: 'Educação & Qualificação', type: 'Híbrido', duration: '6 a 12 Meses', image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&q=80', isIefpSynced: true, link: 'https://www.passaportequalifica.gov.pt/cicLogin.xhtml' },
    { id: 'qual-2', title: 'Processo RVCC Escolar - 12º Ano', description: 'Reconhecimento, Validação e Certificação de Competências para conclusão do Secundário.', category: 'Educação & Qualificação', type: 'Híbrido', duration: '6 a 12 Meses', image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80', isIefpSynced: true, link: 'https://www.passaportequalifica.gov.pt/cicLogin.xhtml' },
    { id: 'qual-3', title: 'RVCC Profissional - Geriatria e Saúde', description: 'Certifique a sua experiência como auxiliar de geriatria de forma rápida e oficial.', category: 'Saúde & Bem-estar', type: 'Híbrido', duration: 'Variável', image: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=800&q=80', isIefpSynced: true, link: 'https://www.passaportequalifica.gov.pt/cicLogin.xhtml' },

    // IEFP Online - Formação Modular / Vida Ativa
    { id: 'mod-1', title: 'Competências Digitais Básicas', description: 'Navegação na internet, email, e segurança online. Ideal para iniciar no mundo digital.', category: 'Educação & Qualificação', type: 'Online', duration: '50h', image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&q=80', isIefpSynced: true, link: 'https://iefponline.iefp.pt/IEFP/pesquisas/search.do?cat=ofertaFormacao' },
    { id: 'mod-2', title: 'Inglês Nível A2-B1', description: 'Formação modular gratuita para certificação linguística. Muito importante na área de serviços.', category: 'Educação & Qualificação', type: 'Em B-learning', duration: '100h', image: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=800&q=80', isIefpSynced: true, link: 'https://iefponline.iefp.pt/IEFP/pesquisas/search.do?cat=ofertaFormacao' },
    { id: 'mod-3', title: 'Primeiros Socorros e SBV', description: 'Módulo de curta duração de Suporte Básico de Vida, requisito para várias profissões.', category: 'Saúde & Bem-estar', type: 'Presencial', duration: '25h', image: 'https://images.unsplash.com/photo-1504439468489-c8920d796a29?w=800&q=80', isIefpSynced: true, link: 'https://iefponline.iefp.pt/IEFP/pesquisas/search.do?cat=ofertaFormacao' },
    { id: 'mod-4', title: 'Programação de Robótica Básica', description: 'Aprenda os fundamentos da eletrónica e robótica. Formação Vida Ativa.', category: 'Tecnologia & Inovação', type: 'Presencial', duration: '150h', image: 'https://images.unsplash.com/photo-1561557944-6e7860d1a7eb?w=800&q=80', isIefpSynced: true, link: 'https://iefponline.iefp.pt/IEFP/pesquisas/search.do?cat=ofertaFormacao' },
    { id: 'mod-5', title: 'Marketing Digital e E-Commerce', description: 'Módulo Intensivo: Crie e promova o seu negócio através da internet e redes profissionais.', category: 'Empreendedorismo', type: 'Online', duration: '200h', image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80', isIefpSynced: true, link: 'https://iefponline.iefp.pt/IEFP/pesquisas/search.do?cat=ofertaFormacao' },

    // Advanced IEFP Technical courses
    { id: 'adv-1', title: 'Tecnologias de Cloud Computing', description: 'Engenharia e Arquitetura AWS/Azure. Formação avançada para o plano Portugal Digital 2026.', category: 'Tecnologia & Inovação', type: 'Online', duration: '350h', image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80', isIefpSynced: true, link: 'https://iefponline.iefp.pt/IEFP/pesquisas/search.do?cat=ofertaFormacao' },
    { id: 'adv-2', title: 'Gestão Ágil de Projetos (Scrum)', description: 'Certificação em Metodologias Ágeis, crucial para IT e Gestão de TI.', category: 'Empreendedorismo', type: 'Em B-learning', duration: '120h', image: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&q=80', isIefpSynced: true, link: 'https://iefponline.iefp.pt/IEFP/pesquisas/search.do?cat=ofertaFormacao' },
    { id: 'adv-3', title: 'Soldadura TIG e MIG/MAG Avançada', description: 'Curso de altíssima empregabilidade em grandes obras nacionais.', category: 'Emprego & Negócios', type: 'Presencial', duration: '400h', image: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=800&q=80', isIefpSynced: true, link: 'https://iefponline.iefp.pt/IEFP/pesquisas/search.do?cat=ofertaFormacao' },

    // Alojamento & Imigração (Courses added by IEFP regarding integration)
    { id: 'int-1', title: 'Cidadania e Empregabilidade em Portugal', description: 'Módulo focado em Literacia Laboral, Direitos e Deveres do Imigrante no SNS e Finanças.', category: 'Direitos & Legalização', type: 'Online', duration: '50h', image: 'https://images.unsplash.com/photo-1473649085228-583485e6e4d7?w=800&q=80', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'int-2', title: 'Higiene e Segurança no Trabalho (HST)', description: 'Certificação inicial HST. Essencial para construção civil, restauração e logística.', category: 'Emprego & Negócios', type: 'Presencial', duration: '35h', image: 'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?w=800&q=80', isIefpSynced: true, link: 'https://www.iefp.pt/formacao' },
    { id: 'aaeif-eng', title: 'Aulas de Inglês - AAEIF', description: 'Curso de inglês para imigrantes focado na integração e comunicação quotidiana.', category: 'Educação & Qualificação', type: 'Presencial/Online', duration: 'Variável', image: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=800&q=80', isIefpSynced: false, link: 'https://www.aaeif.pt/apoio-ao-imigrante/aulas-de-ingl%C3%AAs' }
];
